name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release "src/OpenVASP.CSharpClient.sln"
    - name: Build with test
      run: dotnet test --configuration Release "src/OpenVASP.CSharpClient.sln"
      env: 
        WHISPER_RPC_URL: ${{ secrets.WHISPER_RPC_URL }}
        ETHEREUM_RPC_URL: ${{ secrets.ETHEREUM_RPC_URL }}
